"""add_modifier_names_to_custom_dishes

Revision ID: 1ff9d03fe1d0
Revises: 2415f0ed0e31
Create Date: 2026-05-14 14:30:01.782601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff9d03fe1d0'
down_revision = '2415f0ed0e31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_dishes', sa.Column('size_name', sa.String(length=120), nullable=True))
    op.add_column('custom_dishes', sa.Column('dough_name', sa.String(length=120), nullable=True))
    op.add_column('custom_dishes', sa.Column('sauce_name', sa.String(length=120), nullable=True))
    op.add_column('custom_dishes', sa.Column('toppings_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_dishes', 'toppings_names')
    op.drop_column('custom_dishes', 'sauce_name')
    op.drop_column('custom_dishes', 'dough_name')
    op.drop_column('custom_dishes', 'size_name')
    # ### end Alembic commands ###
