"""add_delivery_fee_to_orders

Revision ID: 2415f0ed0e31
Revises: a43e60a5ebda
Create Date: 2026-05-14 14:13:08.023160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2415f0ed0e31'
down_revision = 'a43e60a5ebda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_fee', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('orders', 'delivery_fee', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_fee')
    # ### end Alembic commands ###
