"""add_modifiers_to_order_items

Revision ID: 46d497b5c903
Revises: 1ff9d03fe1d0
Create Date: 2026-05-14 17:59:33.106891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d497b5c903'
down_revision = '1ff9d03fe1d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('modifiers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'modifiers')
    # ### end Alembic commands ###
