"""make_order_address_nullable_set_null

Revision ID: 94344522df82
Revises: f443f7809fb0
Create Date: 2026-05-10 20:46:24.246644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94344522df82'
down_revision = 'f443f7809fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'addresses', ['address_id'], ['id'])
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
