"""add_payment_method_to_orders

Revision ID: 9c47142d8cb3
Revises: b1d5de465341
Create Date: 2026-05-10 19:29:17.709930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c47142d8cb3'
down_revision = 'b1d5de465341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
