"""add_custom_name_to_order_items

Revision ID: a43e60a5ebda
Revises: 94344522df82
Create Date: 2026-05-14 14:09:29.742309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43e60a5ebda'
down_revision = '94344522df82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('custom_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'custom_name')
    # ### end Alembic commands ###
