"""add_custom_name_to_cart_items

Revision ID: f443f7809fb0
Revises: 9c47142d8cb3
Create Date: 2026-05-10 20:23:06.831398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f443f7809fb0'
down_revision = '9c47142d8cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('custom_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'custom_name')
    # ### end Alembic commands ###
